[project]
name = "simple-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiocron>=2.1",
    "aiohttp>=3.12.14",
    "aiosmtplib>=4.0.1",
    "asyncio>=3.4.3",
    "pydantic>=2.11.7",
]
